### PR TITLE
slimming down the kernel a bit

### PR DESCRIPTION
**Pull request by ghost**
hey, it's tomascus. just bored.

### CODE REVIEW

**Comment by olokos** [comment]
Good stuff, but you forgot to keep the kernel message in commit which disables SysV IPC. Doesn't matter all that much, but it helps when reviewing recent code changes and looking for problems, thanks anyway, will merge. :)

**Comment by ghost** [comment]
lol wth they added reactions to github??

**Comment by olokos** [comment]
This is the place that I actually don't want to see them, lol.

**Comment by olokos** [comment]
This actually breaks external sdcard mounting for some reason.

**Pull request merged**
